### ISSUE TITLE
Feature request - expanded char alert

### ISSUE THREAD

**Issue by tomliv** [Gugu7264/InvisibleAlert.novaextension#1]
Love this extension. Thanks you for creating this.

I'd love to see it expanded to alert other illegal/invisible chars like this VSCode extesion:
https://marketplace.visualstudio.com/items?itemName=nhoizey.gremlins

Thanks for your work!

**Comment by Gugu7264** [comment]
Thanks for your suggestion! I'll add more characters very soon and update the extension, stay tuned!

**Comment by Gugu7264** [comment]
@tomliv The latest extension update adds more invisible characters for checking! Next version will improve performances for large files ;)
