### ISSUE TITLE
Remove unrequired entitlements

### ISSUE THREAD

**Issue by patrickvuarnoz** [Gugu7264/InvisibleAlert.novaextension#2]
Hi there, I stumbled over your extension and was wondering why this extension would launch subprocesses. As far as I could see from your code you do everything in pure javascript, so you could remove this entitlement. For me, personally, it makes an extension more trustworthy if it is self-contained and by that sandboxed.

**Comment by Gugu7264** [comment]
Hi! Thanks for your suggestion, this entitlement was indeed not needed at all. I removed it in the latest version of the extension: https://github.com/Gugu7264/InvisibleAlert.novaextension/commit/cde6be0797bbeea4ba5af460b09f8e430d00a80b
